tag: latest
temporal_url: temporal.temporal-tests.svc.cluster.local:7233

# Worker deployment
worker:
  image: git.odzi.dog/zeephyr/worker
  replicas: 2

# Gateway deployment
gateway:
  image: git.odzi.dog/zeephyr/gateway
  replicas: 1

  service:
    type: ClusterIP

schedules:
  image: git.odzi.dog/zeephyr/schedule-tools

taskQueueName: zeephyr-index
workflows:
  # todo
  # change to zeephyr
  namespace: default

# Database configuration
database:
  url: neo4j+s://zeephyr-index
  user: neo4j
  password: "12344321"
  databaseName: neo4j

#
# Neo4j deployment
neo4j:
  neo4j:
    name: database
    resources:
      cpu: 500m
      memory: 2Gi

    password: "12344321"

  volumes:
    data:
      mode: defaultStorageClass
      defaultStorageClass:
        requests:
          storage: 2Gi