tag: latest
temporalUrl: temporal.temporal.svc.cluster.local:7233

# Worker deployment
worker:
  image: git.odzi.dog/zeephyr/worker
  replicas: 2

  neo4j:
    url: "neo4j://zeephyr-index"
    user: "neo4j"
    password: "u77oD2@&bXwc&XkZrKs@SW5Ks%E"
    databaseName: "neo4j"

  redis:
    url: "redis://zeephyr-index-redis-master:6379"

# Gateway deployment
gateway:
  image: git.odzi.dog/zeephyr/gateway
  replicas: 1

  service:
    type: ClusterIP

schedules:
  image: git.odzi.dog/zeephyr/schedule-tools

taskQueueName: zeephyr-index
workflows:
  # todo
  # change to zeephyr
  namespace: default

#
# Neo4j deployment
neo4j:
  neo4j:
    name: database
    resources:
      cpu: 500m
      memory: 2Gi

    password: "u77oD2@&bXwc&XkZrKs@SW5Ks%E"

  volumes:
    data:
      mode: defaultStorageClass
      defaultStorageClass:
        requests:
          storage: 2Gi

# 
# Redis deployment
redis:
  architecture: standalone
  auth:
    enabled: false