apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workers
spec:
  selector:
    matchLabels:
      app: workers # has to match .spec.template.metadata.labels
  replicas: {{ $.Values.worker.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: workers # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: workers
        image: {{ $.Values.worker.image }}:{{ $.Values.worker.tag }}