{{ $fullname := printf "%s-%s" .Chart.Name "worker" | trunc 63 | trimSuffix "-" }}

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 $.Values.worker.replicas | int }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: worker
        image: {{ $.Values.worker.image }}:{{ $.Values.tag }}
        env:
          - name: TEMPORAL_URL
            value: {{ $.Values.temporal_url }}
          - name: TASK_QUEUE
            value: {{ $.Values.taskQueueName }}
          - name: NAMESPACE
            value: {{ $.Values.workflows.namespace }}
          - name: NEO4J_URI
            value: {{ $.Values.database.url }}
          - name: NEO4J_USERNAME
            value: {{ $.Values.database.user }}
          - name: NEO4J_PASSWORD
            value: {{ $.Values.database.password }}
          - name: NEO4J_DATABASE
            value: {{ $.Values.database.databaseName }}